export const metricsData = [
  {
    title: "Total Revenue",
    value: 2600000,
    isAmount: true,
    stats: 4.5,
    isIncreased: true,
  },
  {
    title: "Average Order value",
    value: 455,
    isAmount: true,
    stats: 0.5,
    isIncreased: false,
  },
  {
    title: "Tickets sold",
    value: 5888,
    isAmount: false,
    stats: 5,
    isIncreased: true,
  },
  {
    title: "Page views",
    value: 8234544,
    isAmount: false,
    stats: 21.2,
    isIncreased: true,
  },
];

export const orderItems = [
  {
    id: 1,
    orderNumber: 1001,
    date: "2024-09-01",
    customer_name: "John Doe",
    event_name: "Summer Festival",
    amount: "150.00",
    image_src: "assets/images/event2.jpg",
  },
  {
    id: 2,
    orderNumber: 1002,
    date: "2024-09-02",
    customer_name: "Jane Smith",
    event_name: "Tech Conference",
    amount: "250.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 3,
    orderNumber: 1003,
    date: "2024-09-03",
    customer_name: "Alice Johnson",
    event_name: "Music Concert",
    amount: "75.50",
    image_src: "assets/images/event4.png",
  },
  {
    id: 4,
    orderNumber: 1004,
    date: "2024-09-04",
    customer_name: "Nithin Kumar",
    event_name: "Art Exhibition",
    amount: "20.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 5,
    orderNumber: 1005,
    date: "2024-09-05",
    customer_name: "Bob Wilson",
    event_name: "Summer Festival",
    amount: "180.00",
    image_src: "assets/images/event2.jpg",
  },
  {
    id: 6,
    orderNumber: 1006,
    date: "2024-09-06",
    customer_name: "Emma Brown",
    event_name: "Tech Conference",
    amount: "300.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 7,
    orderNumber: 1007,
    date: "2024-09-07",
    customer_name: "Michael Davis",
    event_name: "Food Festival",
    amount: "45.00",
    image_src: "assets/images/event4.png",
  },
  {
    id: 8,
    orderNumber: 1008,
    date: "2024-09-08",
    customer_name: "Mega Mind",
    event_name: "Movie Premiere",
    amount: "30.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 9,
    orderNumber: 1009,
    date: "2024-09-09",
    customer_name: "Sarah Lee",
    event_name: "Music Concert",
    amount: "90.00",
    image_src: "assets/images/event2.jpg",
  },
  {
    id: 10,
    orderNumber: 1010,
    date: "2024-09-10",
    customer_name: "David Miller",
    event_name: "Art Exhibition",
    amount: "25.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 11,
    orderNumber: 1011,
    date: "2024-09-11",
    customer_name: "Laura White",
    event_name: "Summer Festival",
    amount: "200.00",
    image_src: "assets/images/event4.png",
  },
  {
    id: 12,
    orderNumber: 1012,
    date: "2024-09-12",
    customer_name: "Chris Green",
    event_name: "Tech Conference",
    amount: "275.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 13,
    orderNumber: 1013,
    date: "2024-09-13",
    customer_name: "Mega Mind",
    event_name: "Food Festival",
    amount: "55.00",
    image_src: "assets/images/event2.jpg",
  },
  {
    id: 14,
    orderNumber: 1014,
    date: "2024-09-14",
    customer_name: "Emily Taylor",
    event_name: "Movie Premiere",
    amount: "35.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 15,
    orderNumber: 1015,
    date: "2024-09-15",
    customer_name: "Daniel Brown",
    event_name: "Music Concert",
    amount: "85.00",
    image_src: "assets/images/event4.png",
  },
  {
    id: 16,
    orderNumber: 1016,
    date: "2024-09-16",
    customer_name: "Olivia Martin",
    event_name: "Art Exhibition",
    amount: "22.50",
    image_src: "assets/images/event1.png",
  },
  {
    id: 17,
    orderNumber: 1017,
    date: "2024-09-17",
    customer_name: "James Wilson",
    event_name: "Summer Festival",
    amount: "175.00",
    image_src: "assets/images/event2.jpg",
  },
  {
    id: 18,
    orderNumber: 1018,
    date: "2024-09-18",
    customer_name: "Mega Mind",
    event_name: "Tech Conference",
    amount: "280.00",
    image_src: "assets/images/event1.png",
  },
  {
    id: 19,
    orderNumber: 1019,
    date: "2024-09-19",
    customer_name: "Sophia Clark",
    event_name: "Food Festival",
    amount: "50.00",
    image_src: "assets/images/event4.png",
  },
  {
    id: 20,
    orderNumber: 1020,
    date: "2024-09-20",
    customer_name: "William Johnson",
    event_name: "Movie Premiere",
    amount: "32.50",
    image_src: "assets/images/event1.png",
  },
];
